spring:
  application:
    name: payment

  datasource:
    url: r2dbc:postgresql://postgresql:5433/payment
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      mode: always

server:
  port: 8081

