TRUNCATE order_items CASCADE;

INSERT INTO order_items (order_id, item_id, quantity) VALUES (5, 15, 10);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (6, 14, 9);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (7, 13, 8);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (15, 12, 7);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (14, 11, 6);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (13, 10, 5);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (12, 9, 4);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (11, 8, 3);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (10, 7, 2);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (9, 6, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (8, 5, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (7, 1, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (6, 1, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (5, 1, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (4, 1, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (3, 1, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (2, 1, 1);
INSERT INTO order_items (order_id, item_id, quantity) VALUES (1, 1, 1);
